version: '3'

services:
    db:
        image: mysql:5.7
        container_name: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: residencias
            MYSQL_USER: root
            MYSQL_PASSWORD: '123456'
        ports: 
            - "3306:3306"
    web:
        build:
            context: ./images/php/
        container_name: php
        depends_on: 
            - db
        volumes: 
            - ./php/:/var/www/html/
            - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports: 
            - "80:80"
        stdin_open: true
        tty: true
